# fly.web.toml

# fly.toml app configuration file generated for acme-turbo web"
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "acme-turbo"
primary_region = "fra"

[build]
dockerfile = "./apps/web/Dockerfile" 

[build.args]
  PROJECT="@acme/web"
  
[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  max_machines_running = 2 
  processes = ["app"]
