name: fly-deploy

on:
   push:
      branches: ["fly"]

jobs:
   deploy:
      name: Deploy Web
      runs-on: ubuntu-latest
      env:
         NEXT_PUBLIC_BASE_URL: ${{ vars.NEXT_PUBLIC_BASE_URL }}
      steps:
         - uses: actions/checkout@v3
         - uses: superfly/flyctl-actions/setup-flyctl@master
         - run: flyctl deploy --config fly.web.toml
              --dockerfile apps/web/Dockerfile --remote-only --wait-timeout=500
           env:
              FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
