name: fly-deploy

on:
   push:
      branches: ["fly"]

jobs:
   - name: Create env file
        run: |
          touch .env
          echo NEXT_PUBLIC_BASE_URL=${{ secrets.NEXT_PUBLIC_BASE_URL }} >> .env
          echo DATABASE_URL=${{ secrets.DATABASE_URL }} >> .env
          echo RESEND_API_KEY=${{ secrets.RESEND_API_KEY }} >> .env
          cat .env
   deploy:
      name: Deploy Web
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v3
         - uses: superfly/flyctl-actions/setup-flyctl@master
         - run: flyctl deploy --config fly.web.toml
              --dockerfile apps/web/Dockerfile --remote-only --wait-timeout=500
           env:
              FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
              NEXT_PUBLIC_BASE_URL: ${{ secrets.NEXT_PUBLIC_BASE_URL }}
              DATABASE_URL: ${{ secrets.DATABASE_URL }}
              RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
